import Song from './controller/class/Song'


const songsList: Song[] = [

    new Song({
        title: 'Circle of Seasons',
        artist: 'Sakuya, Tenma, Banri & Tsumugi',
        img_src: 'assets/images/song_covers/mixed_troupe/circle_of_seasons.png',
        src: 'assets/music/circle_of_seasons.mp3',
    }),
    new Song({
        title: 'Spring has Come!',
        artist: 'Spring Troupe',
        img_src: 'assets/images/song_covers/troupe_song/spring/spring_has_come.png',
        src: 'assets/music/spring_has_come.mp3',
    }),
    new Song({
        title: 'Bokura no Kizuna',
        artist: 'Sakuya Sakuma & Masumi Usui',
        img_src: 'assets/images/song_covers/troupe_song/spring/bokura_no_kizuna.jpg',
        src: 'assets/music/bokura_no_kizuna.mp3',
    }),
    new Song({
        title: 'Akaikami No Cherry Blossom',
        artist: 'Sakuya',
        src: 'assets/music/akaikami_no_cherry_blossom.mp3',
        img_src: 'assets/images/song_covers/character_song/sakuya.png',
    }),
    new Song({
        title: 'Sick Sick Sick',
        artist: 'Masumi Usui',
        img_src: 'assets/images/song_covers/character_song/masumi.png',
        src: 'assets/music/sick_sick_sick.mp3',
    }),
    new Song({
        title: 'Oresama Natsu Summer',
        artist: 'Summer Troupe',
        img_src: 'assets/images/song_covers/mixed_troupe/circle_of_seasons.png',
        src: 'assets/music/oresama_natsu_summer.mp3',
    }),
    new Song({
        title: 'Rakuen Oasis',
        artist: 'Tenma Sumeragi & Yuki Rurikawa',
        img_src: 'assets/images/song_covers/troupe_song/summer/water_me.jpg',
        src: 'assets/music/rakuen_oasis.mp3',
    }),
    new Song({
        title: 'Natsu no Dilemma',
        artist: 'Tenma Sumeragi',
        img_src: 'assets/images/song_covers/characters/faces/tenma.png',
        src: 'assets/music/natsu_no_dilemma.mp3',
    }),
    new Song({
        title: 'Minority',
        artist: 'Yuki Rurikawa',
        img_src: 'assets/images/song_covers/characters/faces/yuki.png',
        src: 'assets/music/minority.mp3',
    }),
    new Song({
        title: 'oneXone',
        artist: 'Autumn Troupe',
        img_src: 'assets/images/song_covers/mixed_troupe/circle_of_seasons.png',
        src: 'assets/music/onexone.mp3',
    }),
    new Song({
        title: 'Ichiya Kagiri no Aibou',
        artist: 'Banri Settsu & Juza Hyodo',
        img_src: 'assets/images/song_covers/troupe_song/autumn/ichiya_kagiri_no_aibou.jpg',
        src: 'assets/music/ichiya_kagiri_no_aibou.mp3',
    }),
    new Song({
        title: 'Super Ultra Easy Mode',
        artist: 'Banri Settsu',
        img_src: 'assets/images/song_covers/characters/faces/banri.png',
        src: 'assets/music/super_ultra_easy_mode.mp3',
    }),
    new Song({
        title: 'Loner',
        artist: 'Juza Hyodo',
        img_src: 'assets/images/song_covers/characters/faces/juza.png',
        src: 'assets/music/loner.mp3',
    }),
    new Song({
        title: 'To Bloom...',
        artist: 'Winter Troupe',
        img_src: 'assets/images/song_covers/troupe_song/winter/to_bloom.png',
        src: 'assets/music/to_bloom.mp3',
    }),
    new Song({
        title: 'Don\'t Cry',
        artist: 'Tsumugi Tsukioka & Tasuku Takato',
        img_src: 'assets/images/song_covers/troupe_song/winter/dont_cry.png',
        src: 'assets/music/dont_cry.mp3',
    }),
    new Song({
        title: 'Keyword',
        artist: 'Tsumugi Tsukioka',
        img_src: 'assets/images/song_covers/characters/faces/tsumugi.png',
        src: 'assets/music/keyword.mp3',
    }),
    new Song({
        title: 'Beyond The Wall',
        artist: 'Tasuku Takato',
        img_src: 'assets/images/song_covers/characters/faces/tasuku.png',
        src: 'assets/music/circle_of_seasons.mp3',
    }),
    new Song({
        title: 'Wonderland A Go Go!',
        artist: 'Masumi Usui & Itaru Chigasaki',
        img_src: 'assets/images/song_covers/troupe_song/spring/wonderland_a_go_go.jpg',
        src: 'assets/music/wonderland_a_go_go.mp3',
    }),
    new Song({
        title: 'Omoide no Nejimaki',
        artist: 'Tsuzuru Minagi & Citron',
        img_src: 'assets/images/song_covers/mixed_troupe/circle_of_seasons.png',
        src: 'assets/music/omoide_no_nejimaki.mp3',
    }),
    new Song({
        title: 'Dandelion no Akubi',
        artist: 'Tsuzuru Minagi',
        img_src: 'assets/images/song_covers/characters/faces/tsuzuru.png',
        src: 'assets/music/circle_of_seasons.mp3',
    }),
    new Song({
        title: 'Gamer\'s High',
        artist: 'Itaru Chigasaki',
        img_src: 'assets/images/song_covers/characters/faces/itaru.png',
        src: 'assets/music/gamers_high.mp3',
    }),
    new Song({
        title: 'Citron no Tadashii Nihongo Koza?',
        artist: 'Citron',
        img_src: 'assets/images/song_covers/characters/faces/citron.png',
        src: 'assets/music/circle_of_seasons.mp3',
    }),
    new Song({
        title: 'Nyanbare! Nya Nya Nya Nya Nyansei',
        artist: 'Yuki Rurikawa & Kazunari Miyoshi',
        img_src: 'assets/images/song_covers/mixed_troupe/circle_of_seasons.png',
        src: 'assets/music/circle_of_seasons.mp3',
    }),
    new Song({
        title: 'Susume! Pirates',
        artist: 'Misumi Ikaruga & Muku Sakisaka',
        img_src: 'assets/images/song_covers/mixed_troupe/circle_of_seasons.png',
        src: 'assets/music/circle_of_seasons.mp3',
    }),
    new Song({
        title: 'Itsuka Oujisama ni...',
        artist: 'Muku Sakisaka',
        img_src: 'assets/images/song_covers/characters/faces/muku.png',
        src: 'assets/music/circle_of_seasons.mp3',
    }),
    new Song({
        title: 'Ichi Ni Sankaku',
        artist: 'Misumi Ikaruga',
        img_src: 'assets/images/song_covers/characters/faces/misumi.png',
        src: 'assets/music/circle_of_seasons.mp3',
    }),
    new Song({
        title: 'Summer Time Love',
        artist: 'Kazunari Miyoshi',
        img_src: 'assets/images/song_covers/characters/faces/kazunari.png',
        src: 'assets/music/circle_of_seasons.mp3',
    }),
    new Song({
        title: 'Just For Myself',
        artist: 'Omi Fushimi & Taichi Nanao',
        img_src: 'assets/images/song_covers/mixed_troupe/circle_of_seasons.png',
        src: 'assets/music/circle_of_seasons.mp3',
    }),
    new Song({
        title: 'Buzama',
        artist: 'Juza Hyodo & Sakyo Furuichi',
        img_src: 'assets/images/song_covers/troupe_song/autumn/buzama.png',
        src: 'assets/music/buzama.mp3',
    }),
    new Song({
        title: 'Living The Dream',
        artist: 'Taichi Nanao',
        img_src: 'assets/images/song_covers/characters/faces/taichi.png',
        src: 'assets/music/circle_of_seasons.mp3',
    }),
    new Song({
        title: 'Finder Goshi no Kizuna',
        artist: 'Omi Fushimi',
        img_src: 'assets/images/song_covers/characters/faces/omi.png',
        src: 'assets/music/circle_of_seasons.mp3',
    }),
    new Song({
        title: 'Ame no Monologue',
        artist: 'Sakyo Furuichi',
        img_src: 'assets/images/song_covers/characters/faces/sakyo.png',
        src: 'assets/music/circle_of_seasons.mp3',
    }),
    new Song({
        title: 'es no Yuutsu',
        artist: 'Homare Arisugawa & Hisoka Mikage',
        img_src: 'assets/images/song_covers/mixed_troupe/circle_of_seasons.png',
        src: 'assets/music/circle_of_seasons.mp3',
    }),
    new Song({
        title: 'Shoutai',
        artist: 'Tasuku Takoto & Azuma Yukishiro',
        img_src: 'assets/images/song_covers/mixed_troupe/circle_of_seasons.png',
        src: 'assets/music/shoutai.mp3',
    }),
    new Song({
        title: 'Traumerei to Kuhaku',
        artist: 'Hisoka Mikage',
        img_src: 'assets/images/song_covers/characters/faces/hisoka.png',
        src: 'assets/music/circle_of_seasons.mp3',
    }),
    new Song({
        title: 'Kiteretsu Poemer',
        artist: 'Homare Arisugawa',
        img_src: 'assets/images/song_covers/character_song/homare.png',
        src: 'assets/music/kiteretsu_poemer.mp3',
    }),
    new Song({
        title: 'Gekkoujou no Aria',
        artist: 'Azuma Yukishiro',
        img_src: 'assets/images/song_covers/character_song/azami.png',
        src: 'assets/music/gekkoujou_no_aria.mp3',
    }),
    new Song({
        title: 'Usotsuki wa Mahou no Hajimari',
        artist: 'Sakuya Sakuma & Chikage Utsuki',
        img_src: 'assets/images/song_covers/mixed_troupe/circle_of_seasons.png',
        src: 'assets/music/circle_of_seasons.mp3',
    }),
    new Song({
        title: 'The Pride Of The Knights',
        artist: 'Itaru Chigasaki & Chikage Utsuki',
        img_src: 'assets/images/song_covers/mixed_troupe/circle_of_seasons.png',
        src: 'assets/music/circle_of_seasons.mp3',
    }),
    new Song({
        title: 'Petenshi no Yuutsu',
        artist: 'Chikage Utsuki',
        img_src: 'assets/images/song_covers/characters/faces/chikage.png',
        src: 'assets/music/petenshi_no_yuutsu.mp3',
    }),
    new Song({
        title: 'Exciting Charmer!',
        artist: 'Tenma Sumeragi & Kumon Hyodo',
        img_src: 'assets/images/song_covers/mixed_troupe/circle_of_seasons.png',
        src: 'assets/music/circle_of_seasons.mp3',
    }),
    new Song({
        title: 'Konton ALL RIGHT!',
        artist: 'Misumi Ikaruga & Kazunari Miyoshi',
        img_src: 'assets/images/song_covers/mixed_troupe/circle_of_seasons.png',
        src: 'assets/music/circle_of_seasons.mp3',
    }),
    new Song({
        title: 'Seiten no Sinker',
        artist: 'Kumon Hyodo',
        img_src: 'assets/images/song_covers/characters/faces/kumon.png',
        src: 'assets/music/circle_of_seasons.mp3',
    }),
    new Song({
        title: 'Second Shot',
        artist: 'Autumn Troupe',
        img_src: 'assets/images/song_covers/mixed_troupe/circle_of_seasons.png',
        src: 'assets/music/second_shot.mp3',
    }),
    new Song({
        title: 'Respawn',
        artist: 'Banri Settsu & Azami Izumida',
        img_src: 'assets/images/song_covers/mixed_troupe/circle_of_seasons.png',
        src: 'assets/music/circle_of_seasons.mp3',
    }),
    new Song({
        title: 'Gaki Atsukai',
        artist: 'Azami Izumida',
        img_src: 'assets/images/song_covers/character_song/azami.png',
        src: 'assets/music/gaki_atsukai.mp3',
    }),
    new Song({
        title: 'Thawing',
        artist: 'Winter Troupe',
        img_src: 'assets/images/song_covers/character_song/thawing.png',
        src: 'assets/music/thawing.mp3',
    }),
    new Song({
        title: 'Step',
        artist: 'Tasuku Takoto & Homare Arisugawa',
        img_src: 'assets/images/song_covers/troupe_song/winter/step.png',
        src: 'assets/music/step.mp3',
    }),
    new Song({
        title: 'Precious To Us',
        artist: 'Winter Troupe',
        img_src: 'assets/images/song_covers/troupe_song/winter/precious_to_us.png',
        src: 'assets/music/precious_to_us.mp3',
    }),
    new Song({
        title: 'Unmask',
        artist: 'Tsumugi Tsukioka & Guy',
        img_src: 'assets/images/song_covers/troupe_song/winter/precious_to_us.png',
        src: 'assets/music/precious_to_us.mp3',
    }),
    new Song({
        title: 'Road to Mantou Master!',
        artist: 'Taichi Nanao & Azami Izumida',
        img_src: 'assets/images/song_covers/troupe_song/winter/precious_to_us.png',
        src: 'assets/music/precious_to_us.mp3',
    }),
    new Song({
        title: 'Hajimari wa Quartet',
        artist: 'Citron & Masumi Usui',
        img_src: 'assets/images/song_covers/troupe_song/winter/precious_to_us.png',
        src: 'assets/music/precious_to_us.mp3',
    }),
    new Song({
        title: 'The Prince In Full Bloom',
        artist: 'Muku Sakisaka & Kumon Hyodo',
        img_src: 'assets/images/song_covers/troupe_song/winter/precious_to_us.png',
        src: 'assets/music/precious_to_us.mp3',
    }),
    new Song({
        title: 'Muddy Hero',
        artist: 'Juza Hyodo & Omi Fushimi',
        img_src: 'assets/images/song_covers/troupe_song/winter/precious_to_us.png',
        src: 'assets/music/precious_to_us.mp3',
    }),
    new Song({
        title: 'Plastic Poker',
        artist: 'Hisoka Mikage & Azuma Yukishiro',
        img_src: 'assets/images/song_covers/troupe_song/winter/precious_to_us.png',
        src: 'assets/music/precious_to_us.mp3',
    }),
    new Song({
        title: 'Growing Pain',
        artist: 'Itaru Chigasaki & Banri Settsu',
        img_src: 'assets/images/song_covers/troupe_song/winter/precious_to_us.png',
        src: 'assets/music/precious_to_us.mp3',
    }),
    new Song({
        title: 'A3 - Haru Natsu Aki Fuyu Blooming',
        artist: 'Sakuya, Tenma, Banri, Tsumugi',
        img_src: 'assets/images/song_covers/troupe_song/winter/precious_to_us.png',
        src: 'assets/music/precious_to_us.mp3',
    }),
    new Song({
        title: 'Natsu tte Pari Pari!',
        artist: 'Summer Troupe',
        img_src: 'assets/images/song_covers/troupe_song/winter/precious_to_us.png',
        src: 'assets/music/precious_to_us.mp3',
    }),
    new Song({
        title: 'Dokkoudou',
        artist: 'Tasuku Takato & Guy',
        img_src: 'assets/images/song_covers/troupe_song/winter/precious_to_us.png',
        src: 'assets/music/precious_to_us.mp3',
    }),
    new Song({
        title: 'A3 Everblooming',
        artist: 'Sakuya, Tenma, Banri, Tsumugi',
        img_src: 'assets/images/song_covers/troupe_song/winter/precious_to_us.png',
        src: 'assets/music/precious_to_us.mp3',
    }),
    new Song({
        title: 'Houkago Midnight',
        artist: 'Misumi Ikaruga & Tsumugi Tsukioka',
        img_src: 'assets/images/song_covers/troupe_song/winter/precious_to_us.png',
        src: 'assets/music/precious_to_us.mp3',
    }),
    new Song({
        title: 'Fukutsu no Chant',
        artist: 'Tsuzuru Minagi & Tasuku Takato',
        img_src: 'assets/images/song_covers/troupe_song/winter/precious_to_us.png',
        src: 'assets/music/precious_to_us.mp3',
    }),
    new Song({
        title: 'Sorachika',
        artist: 'Omi Fushimi & Azami Izumida',
        img_src: 'assets/images/song_covers/troupe_song/winter/precious_to_us.png',
        src: 'assets/music/precious_to_us.mp3',
    }),
    new Song({
        title: 'Suisei to Circus Ou',
        artist: 'Homare Arisugawa & Kazunari Miyoshi',
        img_src: 'assets/images/song_covers/troupe_song/winter/precious_to_us.png',
        src: 'assets/music/precious_to_us.mp3',
    }),
    new Song({
        title: 'MagiClap',
        artist: 'Sakuya Sakuma & Muku Sakisaka',
        img_src: 'assets/images/song_covers/troupe_song/winter/precious_to_us.png',
        src: 'assets/music/precious_to_us.mp3',
    }),
    new Song({
        title: 'Mikansei na Sora de',
        artist: 'Yuki Rurikawa & Taichi Nanao',
        img_src: 'assets/images/song_covers/troupe_song/winter/precious_to_us.png',
        src: 'assets/music/precious_to_us.mp3',
    }),
    new Song({
        title: 'Professional',
        artist: 'Masumi Usui & Tenma Sumeragi',
        img_src: 'assets/images/song_covers/troupe_song/winter/precious_to_us.png',
        src: 'assets/music/precious_to_us.mp3',
    }),
    new Song({
        title: 'Golden Encore',
        artist: 'Chikage & Kumon & Azami & Guy',
        img_src: 'assets/images/song_covers/troupe_song/winter/precious_to_us.png',
        src: 'assets/music/precious_to_us.mp3',
    }),
    new Song({
        title: 'Kikyo no Hana',
        artist: 'Sakyo Furuichi & Azuma Yukishiro',
        img_src: 'assets/images/song_covers/troupe_song/winter/precious_to_us.png',
        src: 'assets/music/precious_to_us.mp3',
    }),
    new Song({
        title: 'Yoi no Mikazuki',
        artist: 'Citron & Guy',
        img_src: 'assets/images/song_covers/troupe_song/winter/precious_to_us.png',
        src: 'assets/music/precious_to_us.mp3',
    }),
    new Song({
        title: 'Scarlet Game',
        artist: 'Hisoka Mikage & Chikage Utsuki',
        img_src: 'assets/images/song_covers/troupe_song/winter/precious_to_us.png',
        src: 'assets/music/precious_to_us.mp3',
    }),
    new Song({
        title: 'Q to Ju',
        artist: 'Kumon Hyodo & Juza Hyodo',
        img_src: 'assets/images/song_covers/troupe_song/winter/precious_to_us.png',
        src: 'assets/music/precious_to_us.mp3',
    }),
    new Song({
        title: 'A3 Act Addict Actor',
        artist: 'Sakuya, Tenma, Banri, Tsumugi',
        img_src: 'assets/images/song_covers/troupe_song/winter/precious_to_us.png',
        src: 'assets/music/precious_to_us.mp3',
    }),
    new Song({
        title: 'My Dictionary',
        artist: 'Sakuya Sakuma',
        img_src: 'assets/images/song_covers/troupe_song/winter/precious_to_us.png',
        src: 'assets/music/precious_to_us.mp3',
    }),
    new Song({
        title: 'Hatsukoi X',
        artist: 'Masumi Usui',
        img_src: 'assets/images/song_covers/troupe_song/winter/precious_to_us.png',
        src: 'assets/music/precious_to_us.mp3',
    }),
    new Song({
        title: 'The storyteller',
        artist: 'Tsuzuru Minagi',
        img_src: 'assets/images/song_covers/troupe_song/winter/precious_to_us.png',
        src: 'assets/music/precious_to_us.mp3',
    }),
    new Song({
        title: 'Real Luck',
        artist: 'Itaru Chigasaki',
        img_src: 'assets/images/song_covers/troupe_song/winter/precious_to_us.png',
        src: 'assets/music/precious_to_us.mp3',
    }),
    new Song({
        title: 'A-I-U-E-Ookina Citron JAPAN',
        artist: 'Citron',
        img_src: 'assets/images/song_covers/troupe_song/winter/precious_to_us.png',
        src: 'assets/music/precious_to_us.mp3',
    }),
    new Song({
        title: 'SEEDS',
        artist: 'Chikage Utsuki',
        img_src: 'assets/images/song_covers/troupe_song/winter/precious_to_us.png',
        src: 'assets/music/precious_to_us.mp3',
    }),
    new Song({
        title: 'Sunflowers',
        artist: 'Tenma Sumeragi',
        img_src: 'assets/images/song_covers/troupe_song/winter/precious_to_us.png',
        src: 'assets/music/precious_to_us.mp3',
    }),
    new Song({
        title: 'Tailor Tailor!',
        artist: 'Yuki Rurikawa',
        img_src: 'assets/images/song_covers/troupe_song/winter/precious_to_us.png',
        src: 'assets/music/precious_to_us.mp3',
    }),
    new Song({
        title: 'Kimi Dake no Prince',
        artist: 'Muku Sakisaka',
        img_src: 'assets/images/song_covers/troupe_song/winter/precious_to_us.png',
        src: 'assets/music/precious_to_us.mp3',
    }),
    new Song({
        title: 'Sankaku Atsume',
        artist: 'Misumi Ikaruga',
        img_src: 'assets/images/song_covers/troupe_song/winter/precious_to_us.png',
        src: 'assets/music/precious_to_us.mp3',
    }),
    new Song({
        title: 'Be Greedy Diver!',
        artist: 'Kazunari Miyoshi',
        img_src: 'assets/images/song_covers/troupe_song/winter/precious_to_us.png',
        src: 'assets/music/precious_to_us.mp3',
    }),
    new Song({
        title: 'Yuukei no Catchball',
        artist: 'Kumon Hyodo',
        img_src: 'assets/images/song_covers/troupe_song/winter/precious_to_us.png',
        src: 'assets/music/precious_to_us.mp3',
    }),
    new Song({
        title: 'RE:portrait',
        artist: 'Banri Settsu',
        img_src: 'assets/images/song_covers/troupe_song/winter/precious_to_us.png',
        src: 'assets/music/precious_to_us.mp3',
    }),
    new Song({
        title: 'MIRAILIGHT',
        artist: 'Juza Hyodo',
        img_src: 'assets/images/song_covers/troupe_song/winter/precious_to_us.png',
        src: 'assets/music/precious_to_us.mp3',
    }),
    new Song({
        title: 'Make My Dream',
        artist: 'Taichi Nanao',
        img_src: 'assets/images/song_covers/troupe_song/winter/precious_to_us.png',
        src: 'assets/music/precious_to_us.mp3',
    }),
    new Song({
        title: 'Lone Wolves',
        artist: 'Omi Fushimi',
        img_src: 'assets/images/song_covers/troupe_song/winter/precious_to_us.png',
        src: 'assets/music/precious_to_us.mp3',
    }),
    new Song({
        title: 'Rojiura wa Itsumo Niwakaame',
        artist: 'Sakyo Furuichi',
        img_src: 'assets/images/song_covers/troupe_song/winter/precious_to_us.png',
        src: 'assets/music/precious_to_us.mp3',
    }),
    new Song({
        title: 'Teenager',
        artist: 'Azami Izumida',
        img_src: 'assets/images/song_covers/troupe_song/winter/precious_to_us.png',
        src: 'assets/music/precious_to_us.mp3',
    }),
    new Song({
        title: 'Zero Limit',
        artist: 'Autumn Troupe',
        img_src: 'assets/images/song_covers/troupe_song/winter/precious_to_us.png',
        src: 'assets/music/precious_to_us.mp3',
    }),
    new Song({
        title: 'Monologue',
        artist: 'Sakuya Sakuma',
        img_src: 'assets/images/song_covers/troupe_song/winter/precious_to_us.png',
        src: 'assets/music/precious_to_us.mp3',
    }),
    new Song({
        title: 'CROSS LINES',
        artist: 'Tsumugi Tsukioka',
        img_src: 'assets/images/song_covers/troupe_song/winter/precious_to_us.png',
        src: 'assets/music/precious_to_us.mp3',
    }),
    new Song({
        title: 'Train Myself',
        artist: 'Tasuku Takato',
        img_src: 'assets/images/song_covers/troupe_song/winter/precious_to_us.png',
        src: 'assets/music/precious_to_us.mp3',
    }),
    new Song({
        title: 'Nachtmusik to Hakugetsu',
        artist: 'Hisoka Mikage',
        img_src: 'assets/images/song_covers/troupe_song/winter/precious_to_us.png',
        src: 'assets/music/precious_to_us.mp3',
    }),
    new Song({
        title: 'Emotion',
        artist: 'Homare Arisugawa',
        img_src: 'assets/images/song_covers/troupe_song/winter/precious_to_us.png',
        src: 'assets/music/precious_to_us.mp3',
    }),
    new Song({
        title: 'Yoake no Junsui',
        artist: 'Azuma Yukishiro',
        img_src: 'assets/images/song_covers/troupe_song/winter/precious_to_us.png',
        src: 'assets/music/precious_to_us.mp3',
    }),
    new Song({
        title: 'For Your Journey ~The Bar\'s Secret~',
        artist: 'Guy',
        img_src: 'assets/images/song_covers/troupe_song/winter/precious_to_us.png',
        src: 'assets/music/precious_to_us.mp3',
    }),
    new Song({
        title: 'The Contract',
        artist: 'Tsumugi Tsukioka & Taichi Nanao',
        img_src: 'assets/images/song_covers/troupe_song/winter/precious_to_us.png',
        src: 'assets/music/precious_to_us.mp3',
    }),
    new Song({
        title: 'Ittkei',
        artist: 'Tenma Sumeragi & Tsuzuru Minagi',
        img_src: 'assets/images/song_covers/troupe_song/winter/precious_to_us.png',
        src: 'assets/music/precious_to_us.mp3',
    }),
    new Song({
        title: 'Mirages Occur During Magical Nights',
        artist: 'Masumi Usui & Chikage Utsuki',
        img_src: 'assets/images/song_covers/troupe_song/winter/precious_to_us.png',
        src: 'assets/music/precious_to_us.mp3',
    }),
    new Song({
        title: 'Shake the Shape',
        artist: 'Misumi Ikaruga & Kumon Hyodo',
        img_src: 'assets/images/song_covers/troupe_song/winter/precious_to_us.png',
        src: 'assets/music/precious_to_us.mp3',
    }),
    new Song({
        title: 'Hungry Neighbors',
        artist: 'Omi Fushimi & Sakyo Furuichi',
        img_src: 'assets/images/song_covers/troupe_song/winter/precious_to_us.png',
        src: 'assets/music/precious_to_us.mp3',
    }),
    new Song({
        title: 'Continuation of the Grand Stay',
        artist: 'Azuma Yukishiro & Guy',
        img_src: 'assets/images/song_covers/troupe_song/winter/precious_to_us.png',
        src: 'assets/music/precious_to_us.mp3',
    }),
    new Song({
        title: 'Wandering Ghost',
        artist: 'Juza Hyodo & Azami Izumida',
        img_src: 'assets/images/song_covers/troupe_song/winter/precious_to_us.png',
        src: 'assets/music/precious_to_us.mp3',
    }),
    new Song({
        title: 'Family Activation',
        artist: 'Itaru Chigasaki & Citron',
        img_src: 'assets/images/song_covers/troupe_song/spring/family_activation.png',
        src: 'assets/music/family_activation.mp3',
    }),
    new Song({
        title: 'Kousui',
        artist: 'Azami Izumida',
        img_src: 'assets/images/song_covers/character_song/azami.png',
        src: 'assets/music/kousui.mp3',
    }),
    new Song({
        title: 'Yume Senri',
        artist: 'Azuma Yukishiro & Citron',
        img_src: 'assets/images/song_covers/mixed_troupe/yume_senri.png',
        src: 'assets/music/yume_senri.mp3',
    }),
];

export default songsList;

// Template
// new Song({
//     title: '',
//     artist: '',
//     img_src: 'assets/images/song_covers/mixed_troupe/circle_of_seasons.png',
//     src: 'assets/music/circle_of_seasons.mp3',
// }),