import Song from './controller/class/Song'


const songsList: Song[] = [

    new Song({
        title: 'Circle of Seasons',
        artist: 'Sakuya, Tenma, Banri & Tsumugi',
        img_src: 'assets/images/song_covers/mixed_troupe/circle_of_seasons.png',
        src: 'assets/music/circle_of_seasons.mp3',
    }),
    new Song({
        title: 'Spring has Come!',
        artist: 'Spring Troupe',
        img_src: 'assets/images/song_covers/troupe_song/spring/spring_has_come.png',
        src: 'assets/music/spring_has_come.mp3',
    }),
    new Song({
        title: 'Bokura no Kizuna',
        artist: 'Sakuya Sakuma & Masumi Usui',
        img_src: 'assets/images/song_covers/troupe_song/spring/bokura_no_kizuna.jpg',
        src: 'assets/music/bokura_no_kizuna.mp3',
    }),
    new Song({
        title: 'Akaikami No Cherry Blossom',
        artist: 'Sakuya',
        src: 'assets/music/akaikami_no_cherry_blossom.mp3',
        img_src: 'assets/images/song_covers/character_song/sakuya.png',
    }),
    new Song({
        title: 'Sick Sick Sick',
        artist: 'Masumi Usui',
        img_src: 'assets/images/song_covers/character_song/masumi.png',
        src: 'assets/music/sick_sick_sick.mp3',
    }),
    new Song({
        title: 'Oresama Natsu Summer',
        artist: 'Summer Troupe',
        img_src: 'assets/images/song_covers/mixed_troupe/circle_of_seasons.png',
        src: 'assets/music/circle_of_seasons.mp3',
    }),
    new Song({
        title: 'Rakuen Oasis',
        artist: 'Tenma Sumeragi & Yuki Rurikawa',
        img_src: 'assets/images/song_covers/troupe_song/summer/water_me.jpg',
        src: 'assets/music/circle_of_seasons.mp3',
    }),
    new Song({
        title: 'Natsu no Dilemma',
        artist: 'Tenma Sumeragi',
        img_src: 'assets/images/song_covers/mixed_troupe/circle_of_seasons.png',
        src: 'assets/music/circle_of_seasons.mp3',
    }),
    new Song({
        title: 'Minority',
        artist: 'Yuki Rurikawa',
        img_src: 'assets/images/song_covers/mixed_troupe/circle_of_seasons.png',
        src: 'assets/music/circle_of_seasons.mp3',
    }),
    new Song({
        title: 'oneXone',
        artist: 'Autumn Troupe',
        img_src: 'assets/images/song_covers/mixed_troupe/circle_of_seasons.png',
        src: 'assets/music/onexone.mp3',
    }),
    new Song({
        title: 'Ichiya Kagiri no Aibou',
        artist: 'Banri Settsu & Juza Hyodo',
        img_src: 'assets/images/song_covers/mixed_troupe/circle_of_seasons.png',
        src: 'assets/music/circle_of_seasons.mp3',
    }),
    new Song({
        title: 'Super Ultra Easy Mode',
        artist: 'Banri Settsu"',
        img_src: 'assets/images/song_covers/mixed_troupe/circle_of_seasons.png',
        src: 'assets/music/circle_of_seasons.mp3',
    }),
    new Song({
        title: 'Loner',
        artist: 'Juza Hyodo',
        img_src: 'assets/images/song_covers/mixed_troupe/circle_of_seasons.png',
        src: 'assets/music/circle_of_seasons.mp3',
    }),
    new Song({
        title: 'To Bloom...',
        artist: 'Winter Troupe',
        img_src: 'assets/images/song_covers/troupe_song/winter/to_bloom.png',
        src: 'assets/music/to_bloom.mp3',
    }),
    new Song({
        title: 'Don\'t Cry',
        artist: 'Tsumugi Tsukioka & Tasuku Takato',
        img_src: 'assets/images/song_covers/troupe_song/winter/dont_cry.png',
        src: 'assets/music/dont_cry.mp3',
    }),
    new Song({
        title: 'Keyword',
        artist: 'Tsumugi Tsukioka',
        img_src: 'assets/images/song_covers/mixed_troupe/circle_of_seasons.png',
        src: 'assets/music/circle_of_seasons.mp3',
    }),
    new Song({
        title: 'Beyond The Wall',
        artist: 'Tasuku Takato',
        img_src: 'assets/images/song_covers/mixed_troupe/circle_of_seasons.png',
        src: 'assets/music/circle_of_seasons.mp3',
    }),
    new Song({
        title: 'Wonderland A Go Go!',
        artist: 'Masumi Usui & Itaru Chigasaki',
        img_src: 'assets/images/song_covers/troupe_song/spring/wonderland_a_go_go.jpg',
        src: 'assets/music/wonderland_a_go_go.mp3',
    }),
    new Song({
        title: 'Omoide no Nejimaki',
        artist: 'Tsuzuru Minagi & Citron',
        img_src: 'assets/images/song_covers/mixed_troupe/circle_of_seasons.png',
        src: 'assets/music/omoide_no_nejimaki.mp3',
    }),
    new Song({
        title: 'Dandelion no Akubi',
        artist: 'Tsuzuru Minagi',
        img_src: 'assets/images/song_covers/mixed_troupe/circle_of_seasons.png',
        src: 'assets/music/circle_of_seasons.mp3',
    }),
    new Song({
        title: 'Gamer\'s High',
        artist: 'Itaru Chigasaki',
        img_src: 'assets/images/song_covers/mixed_troupe/circle_of_seasons.png',
        src: 'assets/music/gamers_high.mp3',
    }),
    new Song({
        title: 'Citron no Tadashii Nihongo Koza?',
        artist: 'Citron',
        img_src: 'assets/images/song_covers/mixed_troupe/circle_of_seasons.png',
        src: 'assets/music/circle_of_seasons.mp3',
    }),
    new Song({
        title: 'Nyanbare! Nya Nya Nya Nya Nyansei',
        artist: 'Yuki Rurikawa & Kazunari Miyoshi',
        img_src: 'assets/images/song_covers/mixed_troupe/circle_of_seasons.png',
        src: 'assets/music/circle_of_seasons.mp3',
    }),
    new Song({
        title: 'Susume! Pirates',
        artist: 'Misumi Ikaruga & Muku Sakisaka',
        img_src: 'assets/images/song_covers/mixed_troupe/circle_of_seasons.png',
        src: 'assets/music/circle_of_seasons.mp3',
    }),
    new Song({
        title: 'Itsuka Oujisama ni...',
        artist: 'Muku Sakisaka',
        img_src: 'assets/images/song_covers/mixed_troupe/circle_of_seasons.png',
        src: 'assets/music/circle_of_seasons.mp3',
    }),
    new Song({
        title: 'Ichi Ni Sankaku',
        artist: 'Misumi Ikaruga',
        img_src: 'assets/images/song_covers/mixed_troupe/circle_of_seasons.png',
        src: 'assets/music/circle_of_seasons.mp3',
    }),
    new Song({
        title: 'Summer Time Love',
        artist: 'Kazunari Miyoshi',
        img_src: 'assets/images/song_covers/mixed_troupe/circle_of_seasons.png',
        src: 'assets/music/circle_of_seasons.mp3',
    }),
    new Song({
        title: 'Just For Myself',
        artist: 'Omi Fushimi & Taichi Nanao',
        img_src: 'assets/images/song_covers/mixed_troupe/circle_of_seasons.png',
        src: 'assets/music/circle_of_seasons.mp3',
    }),
    new Song({
        title: 'Buzama',
        artist: 'Juza Hyodo & Sakyo Furuichi',
        img_src: 'assets/images/song_covers/troupe_song/autumn/buzama.png',
        src: 'assets/music/buzama.mp3',
    }),
    new Song({
        title: 'Living The Dream',
        artist: 'Taichi Nanao',
        img_src: 'assets/images/song_covers/mixed_troupe/circle_of_seasons.png',
        src: 'assets/music/circle_of_seasons.mp3',
    }),
    new Song({
        title: 'Finder Goshi no Kizuna',
        artist: 'Omi Fushimi',
        img_src: 'assets/images/song_covers/mixed_troupe/circle_of_seasons.png',
        src: 'assets/music/circle_of_seasons.mp3',
    }),
    new Song({
        title: 'Ame no Monologue',
        artist: 'Sakyo Furuichi',
        img_src: 'assets/images/song_covers/mixed_troupe/circle_of_seasons.png',
        src: 'assets/music/circle_of_seasons.mp3',
    }),
    new Song({
        title: 'es no Yuutsu',
        artist: 'Homare Arisugawa & Hisoka Mikage',
        img_src: 'assets/images/song_covers/mixed_troupe/circle_of_seasons.png',
        src: 'assets/music/circle_of_seasons.mp3',
    }),
    new Song({
        title: 'Shoutai',
        artist: 'Tasuku Takoto & Azuma Yukishiro',
        img_src: 'assets/images/song_covers/mixed_troupe/circle_of_seasons.png',
        src: 'assets/music/shoutai.mp3',
    }),
    new Song({
        title: 'Traumerei to Kuhaku',
        artist: 'Hisoka Mikage',
        img_src: 'assets/images/song_covers/mixed_troupe/circle_of_seasons.png',
        src: 'assets/music/circle_of_seasons.mp3',
    }),
    new Song({
        title: 'Kiteretsu Poemer',
        artist: 'Homare Arisugawa',
        img_src: 'assets/images/song_covers/character_song/homare.png',
        src: 'assets/music/kiteretsu_poemer.mp3',
    }),


    new Song({
        title: 'Gekkoujou no Aria',
        artist: 'Azuma Yukishiro',
        img_src: 'assets/images/song_covers/character_song/azami.png',
        src: 'assets/music/gekkoujou_no_aria.mp3',
    }),
    new Song({
        title: 'Usotsuki wa Mahou no Hajimari',
        artist: 'Sakuya Sakuma & Chikage Utsuki',
        img_src: 'assets/images/song_covers/mixed_troupe/circle_of_seasons.png',
        src: 'assets/music/circle_of_seasons.mp3',
    }),
    new Song({
        title: 'The Pride Of The Knights',
        artist: 'Itaru Chigasaki & Chikage Utsuki',
        img_src: 'assets/images/song_covers/mixed_troupe/circle_of_seasons.png',
        src: 'assets/music/circle_of_seasons.mp3',
    }),
    new Song({
        title: 'Petenshi no Yuutsu',
        artist: 'Chikage Utsuki',
        img_src: 'assets/images/song_covers/mixed_troupe/circle_of_seasons.png',
        src: 'assets/music/petenshi_no_yuutsu.mp3',
    }),


    new Song({
        title: 'Exciting Charmer!',
        artist: 'Tenma Sumeragi & Kumon Hyodo',
        img_src: 'assets/images/song_covers/mixed_troupe/circle_of_seasons.png',
        src: 'assets/music/circle_of_seasons.mp3',
    }),
    new Song({
        title: 'Konton ALL RIGHT!',
        artist: 'Misumi Ikaruga & Kazunari Miyoshi',
        img_src: 'assets/images/song_covers/mixed_troupe/circle_of_seasons.png',
        src: 'assets/music/circle_of_seasons.mp3',
    }),
    new Song({
        title: 'Seiten no Sinker',
        artist: 'Kumon Hyodo',
        img_src: 'assets/images/song_covers/mixed_troupe/circle_of_seasons.png',
        src: 'assets/music/circle_of_seasons.mp3',
    }),
    new Song({
        title: 'Second Shot',
        artist: 'Autumn Troupe',
        img_src: 'assets/images/song_covers/mixed_troupe/circle_of_seasons.png',
        src: 'assets/music/second_shot.mp3',
    }),
    new Song({
        title: 'Respawn',
        artist: 'Banri Settsu & Azami Izumida',
        img_src: 'assets/images/song_covers/mixed_troupe/circle_of_seasons.png',
        src: 'assets/music/circle_of_seasons.mp3',
    }),
    new Song({
        title: 'Gaki Atsukai',
        artist: 'Azami Izumida',
        img_src: 'assets/images/song_covers/character_song/azami.png',
        src: 'assets/music/gaki_atsukai.mp3',
    }),
    new Song({
        title: 'Thawing',
        artist: 'Winter Troupe',
        img_src: 'assets/images/song_covers/character_song/thawing.png',
        src: 'assets/music/thawing.mp3',
    }),
    new Song({
        title: 'Step',
        artist: 'Tasuku & Homare',
        img_src: 'assets/images/song_covers/troupe_song/winter/step.png',
        src: 'assets/music/step.mp3',
    }),
    new Song({
        title: 'Precious To Us',
        artist: 'Winter Troupe',
        img_src: 'assets/images/song_covers/troupe_song/winter/precious_to_us.png',
        src: 'assets/music/precious_to_us.mp3',
    }),
];

export default songsList;

// Template
// new Song({
//     title: '',
//     artist: '',
//     img_src: 'assets/images/song_covers/mixed_troupe/circle_of_seasons.png',
//     src: 'assets/music/circle_of_seasons.mp3',
// }),


/*
    "A3 - Haru Natsu Aki Fuyu Blooming",
    "Natsu tte Pari Pari! - Summer Troupe",
    "Road to Mantou Master! - Taichi Nanao & Azami Izumida",
    "Unmask - Tsumugi Tsukioka & Guy",
    "Dokkoudou - Tasuku Takato & Guy",
    "Defragmentation - Guy",
    "Hajimari wa Quartet - Citron & Masumi Usui",
    "A3 Everblooming Spring - Spring Troupe",
    "A3 Everblooming Summer - Summer Troupe",
    "A3 Everblooming Autumn - Autumn Troupe",
    "A3 Everblooming Winter - Winter Troupe",
    "The Prince In Full Bloom - Muku Sakisaka & Kumon Hyodo",
    "Muddy Hero - Juza Hyodo & Omi Fushimi",
    "Plastic Poker - Hisoka Mikage & Azuma Yukishiro",
    "Growing Pain - Itaru Chigasaki & Banri Settsu",
    "Houkago Midnight - Misumi Ikaruga & Tsumugi Tsukioka",
    "Fukutsu no Chant - Tsuzuru Minagi & Tasuku Takato",
    "Sorachika - Omi Fushimi & Azami Izumida",
    "Suisei to Circus Ou - Homare Arisugawa & Kazunari Miyoshi",
    "MagiClap - Sakuya Sakuma & Muku Sakisaka",
    "Mikansei na Sora de - Yuki Rurikawa & Taichi Nanao",
    "Professional - Masumi Usui & Tenma Sumeragi",
    "Golden Encore - Chikage & Kumon & Azami & Guy",
    "Kikyo no Hana - Sakyo Furuichi & Azuma Yukishiro",
    "Yoi no Mikazuki - Citron & Guy",
    "Scarlet Game - Hisoka Mikage & Chikage Utsuki",
    "Q to Ju - Kumon Hyodo & Juza Hyodo",
    "A3 Act Addict Actor - Sakuya & Tenma & Banri & Tsumugi",
    "My Dictionary - Sakuya Sakuma",
    "Hatsukoi X - Masumi Usui",
    "The storyteller - Tsuzuru Minagi",
    "Real Luck - Itaru Chigasaki",
    "A-I-U-E-Ookina Citron JAPAN - Citron",
    "SEEDS - Chikage Utsuki",
    "Sunflowers - Tenma Sumeragi",
    "Tailor Tailor! - Yuki Rurikawa",
    "Kimi Dake no Prince - Muku Sakisaka",
    "Sankaku Atsume - Misumi Ikaruga",
    "Be Greedy Diver! - Kazunari Miyoshi",
    "Yuukei no Catchball - Kumon Hyodo",
    "RE:portrait - Banri Settsu",
    "MIRAILIGHT - Juza Hyodo",
    "Make My Dream - Taichi Nanao",
    "Lone Wolves - Omi Fushimi",
    "Rojiura wa Itsumo Niwakaame - Sakyo Furuichi",
    "Teenager - Azami Izumida",
    "Zero Limit - Autumn Troupe",
    "Monologue - Sakuya Sakuma",
    "CROSS LINES - Tsumugi Tsukioka",
    "Train Myself - Tasuku Takato",
    "Nachtmusik to Hakugetsu - Hisoka Mikage",
    "Emotion - Homare Arisugawa",
    "Yoake no Junsui - Azuma Yukishiro",
    "For Your Journey ~The Bar's Secret~ - Guy",
    "The Contract - Tsumugi Tsukioka & Taichi Nanao",
    "Ittkei - Tenma Sumeragi & Tsuzuru Minagi",
    "Mirages Occur During Magical Nights - 	Masumi Usui & Chikage Utsuki",
    "Shake the Shape - Misumi Ikaruga & Kumon Hyodo",
    "Hungry Neighbors - Omi Fushimi & Sakyo Furuichi",
    "Continuation of the Grand Stay - Azuma Yukishiro & Guy",
    "Wandering Ghost - Juza Hyodo & Azami Izumida",
    "Family Activation - Itaru Chigasaki & Citron", 
*/